CREATE DATABASE yeticave 
    DEFAULT CHARACTER SET utf8 
    DEFAULT COLLATE utf8_general_ci;

USE yeticave;
	
CREATE TABLE categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  symbol CHAR(64) NOT NULL UNIQUE,
  name CHAR(64) NOT NULL 
);

CREATE TABLE items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  category_id CHAR(64) NOT NULL,
  name CHAR(255) NOT NULL,
  description TEXT(1024) NOT NULL,
  img_url CHAR(255) NOT NULL,
  price INT NOT NULL,
  step INT UNSIGNED NOT NULL,
  ts_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ts_end TIMESTAMP NOT NULL
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email CHAR(64) NOT NULL,
  password CHAR(64) NOT NULL,
  name CHAR(64) NOT NULL,
  contacts CHAR(255) NOT NULL,
  avatar_url CHAR(255) NOT NULL,
  ts_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  winner_id INT UNSIGNED,
  bet_price INT UNSIGNED NOT NULL,
  ts_betted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX category ON categories(name);
CREATE UNIQUE INDEX email ON users(email);
CREATE INDEX user_name ON users(name);
CREATE INDEX item_name ON items(name);
CREATE INDEX item_price ON items(price);
CREATE FULLTEXT INDEX search_item ON items(name, description);
CREATE INDEX bet_price ON bets(bet_price);

